Support for building JRuby
A patch to build JRuby from source by looking for a build.xml file
and running ant. There's a few more tweaks needed to make JRuby
work since its structure is slightly different. The JRuby stuff
was adapted from the code from the RVM JRuby scripts.

diff --git a/bin/ry b/bin/ry
--- a/bin/ry
+++ b/bin/ry
@@ -176,7 +176,7 @@ ry::build() {
     log "running ./configure --prefix=\"$install_prefix\"..."
     ./configure --prefix="$install_prefix" "${@:2}"
   else
-    log "no ./configure or script found, skipping..."
+    log "no ./configure script found, skipping..."
   fi
 
   if [[ -f ./Makefile ]]; then
@@ -185,7 +185,23 @@ ry::build() {
     PREFIX="$install_prefix" make install
   elif [[ -x ./installer ]]; then
     log "./installer script found, running ./install --auto=\"$install_prefix\""
-    ./installer --auto="$install_prefix"
+    ./installer --auto="$install_prefix" "${@:2}"
+  elif [[ -f ./build.xml ]]; then
+    log "build.xml found, building JRuby with ant"
+    exists? ant || abort "ant is required to build this ruby."
+    ant jar
+
+    for binary in jirb jruby jgem ; do
+      log "linking "$binary" as ${binary#j}"
+      ln -fs "$binary" "bin/${binary#j}"
+    done
+
+    log "linking bin and lib directories"
+    ln -s "$builddir/bin" "$install_prefix/bin"
+    ln -s "$builddir/lib" "$install_prefix/lib"
+
+    log "Setting the JRUBY_HOME environment variable to $RY_LIB/current. It's recommended to add it to your shell profile."
+    export JRUBY_HOME=$RY_LIB/current
   elif [[ -f ./Rakefile ]]; then
     log "Rakefile found, building with PREFIX=\"$install_prefix\" rake install"
     exists? rake || abort "rake is required to build this ruby."
